### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by huerlisi** [nicoboss/Floatmotion#2]
Whenever one finds a (new) project on github, a README (like markdown...) is a great start.

It quickly helps deciding if this project is something one would like to use (and hopefully to contribute to).

It should say a couple of words about what the project is about, how to install, and maybe how to use.

Liebe Grüess
Simon

**Comment by nicoboss** [comment]
Thanks a lot for your god advices. I added one. I'll add the installation and using thing when I'm so far that I have a playable game. Maybe I'll also make an English translation if I have time.

Liebe Grüsse
Nico
